name: EvelynsDecor
favicon: null
layout_spectrum: 0.8314436131622642
typography_spectrum: 0.023752158507704735
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.08174177445471287
  lightness: 0.6660139204468578
  saturation: 0.8474765671417117
  rhythmicContrast: 0.06246647681109607
purpose: []
